trigger:
  branches:
    include:
    - "master"

variables:
  - name: vmImage
    value: 'windows-2019'
  - group: serviceGroup-variables

resources:
  repositories:
    - repository: sources
      type: git
      name: ccoe/sources
      ref: refs/heads/master

stages:
- template: Pipelines/stages/publishArtifact.yml@sources
  parameters:
    vmImage: '${{ variables.vmImage }}'

- template: ci/stages/deployInfra.yml
  parameters:
    environmentName: 'dev001'
    dependsOn: 'publish_pipeline_artifacts'
    jsonPath: $(jsonPath)
    location: 'West Europe'
    locationShort: 'weu'
    serviceGroupShortName: $(serviceGroupShortName)
    vmImage: '${{ variables.vmImage }}'

#- template: ci/stages/deployInfra.yml
#  parameters:
#    environmentName: 'tst001'
#    dependsOn: 'deploy_dev001'
#    jsonPath: '${{ variables.jsonPath }}'
#    location: 'West Europe'
#    locationShort: 'weu'
#    serviceGroupShortName: $(serviceGroupShortName)
#    vmImage: '${{ variables.vmImage }}'
#
#- template: ci/stages/deployInfra.yml
#  parameters:
#    environmentName: 'acc001'
#    dependsOn: 'deploy_tst001'
#    jsonPath: '${{ variables.jsonPath }}'
#    location: 'West Europe'
#    locationShort: 'weu'
#    serviceGroupShortName: $(serviceGroupShortName)
#    vmImage: '${{ variables.vmImage }}'
#
#- template: ci/stages/deployInfra.yml
#  parameters:
#    environmentName: 'prd001'
#    dependsOn: 'deploy_acc001'
#    jsonPath: '${{ variables.jsonPath }}'
#    location: 'West Europe'
#    locationShort: 'weu'
#    serviceGroupShortName: $(serviceGroupShortName)
#    vmImage: '${{ variables.vmImage }}'
