parameters:
  connectedServiceName: ''
  dependsOn: ''
  environmentName: ''
  location: ''
  locationShort: ''
  serviceGroup: ''
  serviceName: ''
  sourcesPipeline: ''
  sourcesProject: ''
  vmImage: ''

jobs:
  - deployment: ${{ parameters.serviceName }}
    dependsOn:
    - ${{ if parameters.dependsOn }}:
      - ${{ parameters.dependsOn }}
    displayName: "${{ format('Deploy {0}', parameters.serviceName) }}"
    pool:
      vmImage: ${{ parameters.vmImage }}
    environment: ${{ parameters.environmentName }}
    strategy:
        runOnce:
          deploy:
            steps:
            - template: ../steps/artifactsAndNaming.yml
              parameters:
                connectedServiceName: '${{ parameters.connectedServiceName }}'
                location: '${{ parameters.location }}'
                resourceGroupName: "${{ format('{0}-{1}-{2}-{3}-rsg', parameters.serviceGroup, parameters.environmentName, parameters.locationShort, parameters.serviceName) }}"
                sourcesPipeline: '${{ parameters.sourcesPipeline }}'
                sourcesProject: '${{ parameters.sourcesProject }}'

            - task: AzureResourceGroupDeployment@2
              displayName: 'Deploy Log Analytics Workspace'
              inputs:
                azureSubscription: '${{ parameters.connectedServiceName }}'
                resourceGroupName: "${{ format('{0}-{1}-{2}-{3}-rsg', parameters.serviceGroup, parameters.environmentName, parameters.locationShort, parameters.serviceName) }}"
                location: '${{ parameters.location }}'
                csmFile: '$(System.ArtifactsDirectory)/Sources/Templates/logAnalyticsWorkspace.json'
                overrideParameters: '-workspaceName $(logAnalyticsWorkspaceName)'

            - task: AzureResourceGroupDeployment@2
              displayName: 'Deploy Key Vault'
              inputs:
                azureSubscription: '${{ parameters.connectedServiceName }}'
                resourceGroupName: "${{ format('{0}-{1}-{2}-{3}-rsg', parameters.serviceGroup, parameters.environmentName, parameters.locationShort, parameters.serviceName) }}"
                location: '${{ parameters.location }}'
                csmFile: '$(System.ArtifactsDirectory)/Sources/Templates/keyVault.json'
                csmParametersFile: '../buildartifacts.copyandpublish/$(environmentName)/keyVault.param.json'
                overrideParameters: '-keyVaultName $(keyVaultName)'

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Deploy Audit Log Collection'
              inputs:
                deploymentScope: 'Subscription'
                azureResourceManagerConnection: '${{ parameters.connectedServiceName }}'
                subscriptionId: '$(subscriptionId)'
                location: '${{ parameters.location }}'
                csmFile: '$(System.ArtifactsDirectory)/Sources/Templates/activityLogs.json'
                overrideParameters: '-diagnosticResourceGroupName $(resourceGroupName) -diagnosticOmsWorkspaceName $(logAnalyticsWorkspaceName) -diagnosticOmsSubscriptionID $(subscriptionId)'
                deploymentMode: 'Incremental'

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Deploy Security Centre'
              inputs:
                deploymentScope: 'Subscription'
                azureResourceManagerConnection: '${{ parameters.connectedServiceName }}'
                subscriptionId: '$(subscriptionId)'
                location: '${{ parameters.location }}'
                csmFile: '$(System.ArtifactsDirectory)/Sources/Templates/securityCenter.json'
                deploymentMode: 'Incremental'