parameters:
  dependsOn: ''
  environmentName: ''
  jsonPath: ''
  location: ''
  locationShort: ''
  serviceGroupShortName: ''
  vmImage: ''

stages:
  - stage: deploy_${{ parameters.environmentName }}
    dependsOn: '${{ parameters.dependsOn }}'
    displayName: "${{ format('deploy {0}', parameters.environmentName) }}"
    jobs:
    - template: Pipelines/jobs/deployCore.yml@sources
      parameters:
        connectedServiceName: "${{ format('{0}-{1}-sub-spn', parameters.serviceGroupShortName, parameters.environmentName) }}"
        environmentName: '${{ parameters.environmentName }}'
        dependsOn: ''
        jsonPath: '${{ parameters.jsonPath }}'
        location: '${{ parameters.location }}'
        locationShort: '${{ parameters.locationShort }}'
        serviceGroupShortName: '${{ parameters.serviceGroupShortName }}'
        vmImage: '${{ parameters.vmImage }}'

    - template: Pipelines/jobs/deployNtwk.yml@sources
      parameters:
        connectedServiceName: "${{ format('{0}-{1}-sub-spn', parameters.serviceGroupShortName, parameters.environmentName) }}"
        dependsOn: 'core'
        environmentName: '${{ parameters.environmentName }}'
        jsonPath: '${{ parameters.jsonPath }}'
        location: '${{ parameters.location }}'
        locationShort: '${{ parameters.locationShort }}'
        serviceGroupShortName: '${{ parameters.serviceGroupShortName }}'
        vmImage: '${{ parameters.vmImage }}'